
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.sql_interprete.main.gramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOR = 18;
  public static final int PUNTO = 13;
  public static final int INSERTAR = 3;
  public static final int IGUAL = 17;
  public static final int MENOR_IGUAL = 20;
  public static final int PALABRA = 22;
  public static final int ELIMINAR = 5;
  public static final int MAYOR_IGUAL = 21;
  public static final int POR = 16;
  public static final int FILTRAR = 7;
  public static final int VALORES = 8;
  public static final int ASIGNAR = 9;
  public static final int ACTUALIZAR = 4;
  public static final int COMA = 14;
  public static final int MAYOR = 19;
  public static final int EOF = 0;
  public static final int PARANTESIS_I = 11;
  public static final int COMILLA = 10;
  public static final int error = 1;
  public static final int PARANTESIS_D = 12;
  public static final int EN = 6;
  public static final int ENTERO = 23;
  public static final int SELECCIONAR = 2;
  public static final int PUNTO_Y_COMA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECCIONAR",
  "INSERTAR",
  "ACTUALIZAR",
  "ELIMINAR",
  "EN",
  "FILTRAR",
  "VALORES",
  "ASIGNAR",
  "COMILLA",
  "PARANTESIS_I",
  "PARANTESIS_D",
  "PUNTO",
  "COMA",
  "PUNTO_Y_COMA",
  "POR",
  "IGUAL",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "PALABRA",
  "ENTERO"
  };
}

